# Generated by Django 3.1.3 on 2020-11-19 22:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_as_primary', to=settings.AUTH_USER_MODEL)),
                ('usertwo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_as_secondary', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('userone', 'usertwo')},
            },
        ),
        migrations.CreateModel(
            name='ListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.list')),
            ],
        ),
    ]
