# Generated by Django 3.1.3 on 2020-11-23 03:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('list', '0005_auto_20201123_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='userone',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_as_primary', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='list',
            name='usertwo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_as_secondary', to=settings.AUTH_USER_MODEL),
        ),
    ]
