# Generated by Django 3.1.3 on 2020-12-03 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0011_auto_20201201_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='list.list'),
        ),
    ]
